controller_manager:
  ros__parameters:
    update_rate: 500

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

leg_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - Motor1
      - Motor5
      - Motor9
      - Motor2
      - Motor6
      - Motor10
      - Motor3
      - Motor7
      - Motor11
      - Motor4
      - Motor8
      - Motor12
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
    
